### PR TITLE
Added Responsiveness to page

### PR DESCRIPTION
**Pull request by rupalisingh**
Hi @euhidaman ,
I have made the page responsive using tailwind CSS. I have not touched the header of the page, as I believe that you are already working on it.

Also I am participating in Hacktoberfest 2021, so I request you to add 'hacktoberfest-accepted' label to my pull request, so that it counts

Thank you

### CODE REVIEW

**Review by euhidaman — COMMENTED** [review]
I can't see any of the features/changes made by you, due to the changes made in `package.json` file.<br>
This is the output, that I'm getting : 
Screenshot_4

And, as a project maintainer, I am not simply allowed to give out the `hacktoberfest-accepted` label without seeing the actual contribution. But, if you can provide the screenshots/GIFs of your work, in the comments here, then I can provide you with the `hacktoberfest-accepted` label, to  +1 your Hacktoberfest contributions.

**Comment by rupalisingh** [comment]
Hi @euhidaman,
I had to install tailwind-scrollbar-hide plugin, to hide the overflow scrollbar.

I suggest you to install that plugin, then It will work 
Check the plugin from here - https://www.npmjs.com/package/tailwind-scrollbar-hide

**Comment by rupalisingh** [comment]
https://user-images.githubusercontent.com/32214955/137614220-f1949e36-3901-487b-9f65-cad99d6852da.mp4

hi @euhidaman, Here is the mp4 video of my work. Hope you like it

**Comment by euhidaman** [comment]
Thank you for contributing !!
I was able to fix that error, and it works perfectly fine now !!

**Pull request merged**
