### PR TITLE
Made food options and filter buttons menu responsive

### PR DESCRIPTION
**Pull request by sungod12**
-The filter buttons and food options are now responsive on almost all devices.
-Added scrollbar instead of ColoredLine component, in case both the filter buttons and food options are not visible.
-Added comments wherever changes were made in previous commit as well as this commit.
 
Please review the changes and check if they if they display correctly.

Thanks. Please accept this under hacktoberfest-accepted label.

### CODE REVIEW

**Comment by sungod12** [comment]
Please review @euhidaman .

**Review by euhidaman — CHANGES_REQUESTED** [review]
First of all, Thank you for contributing !!

But, I would like you to do a few changes:
Screenshot_3
- The FilterButton's words in your code are in different lines(they should be in a single line).
-  And as you can see in the below screenshot of the actual Zomato website, that the coloredLine component is also present. So, please try to incorporate it into the website as well.

Actual Zomato colored line and FilterButtons screenshot : 
Screenshot_4

**Note : Please try to keep the layout of this clone website, as much close to the original as possible**

**Comment by sungod12** [comment]
Zomato website is not that responsive.

**Comment by sungod12** [comment]
That filtered options doesnt look good going left.

**Comment by euhidaman** [comment]
> That filtered options doesnt look good going left.

It's okay. But, if the current changes are incorporated, then it won't look good on screens above 1000px too.

**Comment by sungod12** [comment]
> > That filtered options doesnt look good going left.
> 
> It's okay. But, if the current changes are incorporated, then it won't look good on screens above 1000px too.

okay. I will make filterButtons changes. But that red line is not possible.

**Comment by euhidaman** [comment]
Your changes in the FoodOptions.js component is good though. 
As it brings the layout of this clone website, as closer to the actual website.

**Comment by euhidaman** [comment]
> > > That filtered options doesnt look good going left.
> > 
> > 
> > It's okay. But, if the current changes are incorporated, then it won't look good on screens above 1000px too.
> 
> okay. I will make filterButtons changes. But that red line is not possible.

It's okay. No need of making changes to the FilterButtons and coloredLine component [Leave it].
Just keep the foodOptions component, in your pull request.

**Comment by sungod12** [comment]
okay

**Comment by sungod12** [comment]
done removed those files and changes.

**Comment by sungod12** [comment]
> Your changes in the FoodOptions.js component is good though. As it brings the layout of this clone website, as closer to the actual website.

yep,thats why made changes.

**Review by euhidaman — APPROVED** [review]
Thank you for contributing, and making this project great !!☺

**Do star this project, to make it popular !! ⭐**

**Pull request merged**
